baseURL = "http://kopalova.sk"
languageCode = "en"
title = "Greenlandic"
theme = "hugo-nuo"
enableRobotsTXT = true
canonifyurls = true

# Google Analytics UA number
googleAnalytics = "UA-120660550-1"

# Copyright of your post
copyright = "© 2018 Licensed under a Creative Commons Attribution-NonCommercial 4.0 International License. Please give source if you quote or reproduce."

# Initial site menu, you can extend menu with content.
#[[menu.main]]
#  name = "Home"
#  weight = 10
#  identifier = "home"
#  url = "/"

# Add your own params here
[params]
  author = "Eva Kopalova"
  avatar = "/img/logo_clean.svg"
  seotitle = "Kalaallisut"
  subtitle = "Random Notes of a Learner"
  description = "Random notes on grammar, vocabulary, and pronunciation of Greenlandic."
  paginate = 10
  favicon = "/img/favicon.png"
  
  # Choose your social networks
  email = "i.am.learning.greenlandic<span display=\"none\" class=\"hehe\"/>@domain.com"
